# Generated by Django 3.2.25 on 2024-12-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_withdraw_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Category',
            field=models.CharField(choices=[('Novels', 'Novels'), ('Short stories', 'Short stories'), ('Poetry', 'Poetry'), ('Flash fiction', 'Flash fiction'), ('Self help', 'Self help'), ('Biographies & Memoirs', 'Biographies & Memoirs'), ('Personal development', 'Personal development'), ('History', 'History'), ('True crime', 'True crime'), ('Textbooks', 'Textbooks'), ('Research papers & white papers', 'Research papers & white papers'), ('Study guides', 'Study guides'), ('How-to guides & tutorials', 'How-to guides & tutorials'), ('Business strategy guides', 'Business strategy guides'), ('Marketing and sales e-books', 'Marketing and sales e-books'), ('Entrepreneurship guides', 'Entrepreneurship guides'), ('Financial planning', 'Financial planning'), ('Nutrition guides', 'Nutrition guides'), ('Workout and fitness plans', 'Workout and fitness plans'), ('Mental health & wellness', 'Mental health & wellness'), ('Meditation and mindfulness e-books', 'Meditation and mindfulness e-books'), ('Coding and programming tutorials', 'Coding and programming tutorials'), ('Software manuals', 'Software manuals'), ('IT and networking guides', 'IT and networking guides'), ('Artificial intelligence & machine learning', 'Artificial intelligence & machine learning'), ('Photography tutorials', 'Photography tutorials'), ('Painting and drawing guides', 'Painting and drawing guides'), ('Writing and storytelling techniques', 'Writing and storytelling techniques'), ('Crafting & DIY projects', 'Crafting & DIY projects'), ('Recipe collections', 'Recipe collections'), ('Specialized diet guides', 'Specialized diet guides'), ('Meal planning and prep', 'Meal planning and prep'), ('Parenting advice', 'Parenting advice'), ('Marriage and relationship counseling', 'Marriage and relationship counseling'), ('Family planning guides', 'Family planning guides'), ('Childcare and development', 'Childcare and development'), ('Travel guides', 'Travel guides'), ('Destination reviews', 'Destination reviews'), ('Adventure stories', 'Adventure stories'), ('Travel planning and budgeting', 'Travel planning and budgeting'), ('Personal finance e-books', 'Personal finance e-books'), ('Investment strategies', 'Investment strategies'), ('Retirement planning', 'Retirement planning'), ('Budgeting tips', 'Budgeting tips'), ('Meditation and mindfulness books', 'Meditation and mindfulness books'), ('Philosophy and life purpose e-books', 'Philosophy and life purpose e-books'), ('Time management and productivity', 'Time management and productivity'), ('Self-improvement and motivation', 'Self-improvement and motivation'), ('Life coaching guides', 'Life coaching guides'), ('Work-life balance', 'Work-life balance'), ('Legal guides and contracts', 'Legal guides and contracts'), ('HR and employment handbooks', 'HR and employment handbooks'), ('Professional development', 'Professional development'), ('Real estate investment guides', 'Real estate investment guides'), ('Property management manuals', 'Property management manuals'), ('Buying and selling homes', 'Buying and selling homes')], max_length=200, null=True),
        ),
    ]
