# Generated by Django 3.2.25 on 2025-01-09 13:00

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adobetemplate',
            name='Image',
            field=models.ImageField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='adobetemplate',
            name='Preview_Video',
            field=models.FileField(blank=True, help_text='Optional', null=True, upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='adobetemplate',
            name='Template',
            field=models.FileField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='book',
            name='Book',
            field=models.FileField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='book',
            name='Image',
            field=models.ImageField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='business',
            name='Image',
            field=models.ImageField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='business',
            name='Preview_Video',
            field=models.FileField(blank=True, help_text='Optional', null=True, upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='business',
            name='Product',
            field=models.FileField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='cad',
            name='Image',
            field=models.ImageField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='cad',
            name='Preview_Video',
            field=models.FileField(blank=True, help_text='Optional', null=True, upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='cad',
            name='Product',
            field=models.FileField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='desktoptemplate',
            name='Image',
            field=models.ImageField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='desktoptemplate',
            name='Preview_Video',
            field=models.FileField(blank=True, help_text='Optional', null=True, upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='desktoptemplate',
            name='Template',
            field=models.FileField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='digitalart',
            name='Image',
            field=models.ImageField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='digitalart',
            name='Preview_Video',
            field=models.FileField(blank=True, help_text='Optional', null=True, upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='digitalart',
            name='Product',
            field=models.FileField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='image',
            name='Image',
            field=models.ImageField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='image',
            name='Image_download',
            field=models.FileField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='microsofttemplate',
            name='Image',
            field=models.ImageField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='microsofttemplate',
            name='Preview_Video',
            field=models.FileField(blank=True, help_text='Optional', null=True, upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='microsofttemplate',
            name='Template',
            field=models.FileField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='mobiletemplate',
            name='Image',
            field=models.ImageField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='mobiletemplate',
            name='Preview_Video',
            field=models.FileField(blank=True, help_text='Optional', null=True, upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='mobiletemplate',
            name='Template',
            field=models.FileField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='Image',
            field=models.ImageField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='Preview_Video',
            field=models.FileField(blank=True, help_text='Optional', null=True, upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='Product',
            field=models.FileField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='music',
            name='Image',
            field=models.ImageField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='music',
            name='Preview_Audio',
            field=models.FileField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='music',
            name='Product',
            field=models.FileField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='printable',
            name='Image',
            field=models.ImageField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='printable',
            name='Product',
            field=models.FileField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='project',
            name='Image',
            field=models.ImageField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='project',
            name='Preview_Video',
            field=models.FileField(blank=True, help_text='Optional', null=True, upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='project',
            name='Project',
            field=models.FileField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='software',
            name='Image',
            field=models.ImageField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='software',
            name='Preview_Video',
            field=models.FileField(blank=True, help_text='Optional', null=True, upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='software',
            name='Product',
            field=models.FileField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='Image',
            field=models.ImageField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='Preview_Video',
            field=models.FileField(blank=True, help_text='Optional', null=True, upload_to='home/', validators=[web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='Template',
            field=models.FileField(upload_to='home/', validators=[web.models.validate_file_size]),
        ),
    ]
